import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Google Fonts link */}
        <link 
          rel="stylesheet" 
          href="https://fonts.googleapis.com/css2?family=Fauna+One:wght@400;700&display=swap" 
        />
      </head>
      <body className={`${inter.className} font-fauna`}>
        {children}
      </body>
    </html>
  );
}
