"""Add extra columns to paper

Revision ID: 5f376726b022
Revises: 63030322dce6
Create Date: 2024-08-18 17:12:57.560605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f376726b022'
down_revision = '63030322dce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('doi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('publish_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('abstract', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('synopsis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relevance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=False))
        batch_op.drop_column('url')
        batch_op.drop_column('relevance')
        batch_op.drop_column('synopsis')
        batch_op.drop_column('abstract')
        batch_op.drop_column('publish_date')
        batch_op.drop_column('doi')
        batch_op.drop_column('publication')

    # ### end Alembic commands ###
